spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      routes:
        - id: product-catalog
          uri: lb://product-catalog
          predicates:
            - Path=/product/**
      discovery:
        locator:
          enabled: true
server:
  port: 8888

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8012/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability:
        1.0

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
          loadbalancer: trace
